In [2]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

In [3]:
obj=Series([4,7,-5,3])
print(obj.values)
print(obj.index)

[ 4  7 -5  3]
RangeIndex(start=0, stop=4, step=1)


In [4]:
obj2=Series([4,7,-5,3],index=['d','b','a','c'])
obj2.index


Index(['d', 'b', 'a', 'c'], dtype='object')

In [5]:
obj2['d']=6
obj2[['c','a','d']]

c    3
a   -5
d    6
dtype: int64

In [6]:
print(obj2)
obj2[obj2>2]

d    6
b    7
a   -5
c    3
dtype: int64


d    6
b    7
c    3
dtype: int64

In [7]:
'b' in obj2
'e' in obj2

False

In [8]:
sdata={'Ohio':35000, 'Texas':71000,'Oregon':16000,'Utah':5000}
obj3=Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [9]:
states=['California','Ohio','Oregon','Texas']
obj4=Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [10]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [11]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [12]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [13]:
obj3+obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [14]:
obj4.name='population'

In [15]:
obj4.index.name='state'

In [16]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [17]:
obj.index=['Bob','Steve','Jeff','Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [18]:
data={'state':['Ohio','Ohio','Ohio','Nevada','Nevada'],'year':[2000,2001,2002,2001,2002],
      'pop':[1.5,1.7,3.6,2.4,2.9]}
frame=DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [19]:
DataFrame(data, columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [20]:
frames2=DataFrame(data,columns=['year','state','pop','debt'],
                 index=['one','two','three','four','five'])
frames2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [22]:
frames2['debt']=16.5
frames2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [23]:
frames2['debt']=np.arange(5.)
frames2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0

In [24]:
val=Series([-1.2,-1.5,-1.7],index=['two','four','five'])
frames2['debt']=val
frames2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [25]:
frames2['eastern']=frames2.state=='Ohio'
frames2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False

In [26]:
del frames2['eastern']
frames2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [27]:
pop={'Nevada':{2001:2.4,2002:2.9},
    ....:'Ohio':{2000:1.5,2001:1.7,2002:3.6}}
frames3=DataFrame(pop)
frames3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [28]:
frames3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [29]:
DataFrame(pop,index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [30]:
pdata={'Ohio':frames3['Ohio'][:-1],
      'Nevada':frames3['Nevada'][:2]}
DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [31]:
frames3.index.name='year'; frames3.columns.name='state'
frames3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [32]:
frames3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [33]:
frames2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7]], dtype=object)

In [34]:
obj=Series(range(3),index=['a','b','c'])
index=obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [35]:
index[1:]

Index(['b', 'c'], dtype='object')

In [36]:
index= pd.Index(np.arange(3))
obj2=Series([1.5,-2.5,0],index=index)
obj2.index is index

True

In [37]:
'Ohio' in frames3.columns

True

In [38]:
2003 in frames3.index

False

In [39]:
obj=Series([4.5,7.2,-5.3,3.6],index=['d','b','a','c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [40]:
obj2=obj.reindex(['a','b','c','d','e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [41]:
obj.reindex(['a','b','c','d','e'],fill_value=0)

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [42]:
obj3=Series(['blue','purple','yellow'],index=[0,2,4])
obj3.reindex(range(6),method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [43]:
frame=DataFrame(np.arange(9).reshape((3,3)),index=['a','c','d'],columns=['Ohio','Texas','California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [44]:
frame2=frame.reindex(['a','b','c','d'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [45]:
states=['Texas','Utah','California']
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [46]:
obj=Series(np.arange(5.),index=['a','b','c','d','e'])
new_obj=obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [47]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [48]:
data=DataFrame(np.arange(16).reshape((4,4)),index=['Ohio','Colorado','Utah','New York'],
              columns=['one','two','three','four'])
data.drop(['Colorado','Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [49]:
data.drop('two',axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [50]:
data.drop(['two','four'],axis=1)

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [51]:
obj=Series(np.arange(4.),index=['a','b','c','d'])
obj['b']

1.0

In [52]:
print(obj[1])
print(obj[2:4])
print(obj[['b','a','d']])
print(obj[[1,3]])
print(obj[obj<2])

1.0
c    2.0
d    3.0
dtype: float64
b    1.0
a    0.0
d    3.0
dtype: float64
b    1.0
d    3.0
dtype: float64
a    0.0
b    1.0
dtype: float64


In [53]:
obj['b','c']=5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [99]:
data=pd.DataFrame(np.arange(16).reshape((4,4)),
               index=['Ohio','Colorado','Utah','New York'],
               columns=['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [100]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [101]:
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [102]:
data[data<5]=0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [105]:
s1=Series([7.3,-2.5,3.4,1.5],index=['a','c','d','e'])
s2=Series([-2.1,3.6,-1.5,4,3.1],index=['a','c','e','f','g'])
s1
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [106]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [107]:
df1=DataFrame(np.arange(9.).reshape((3,3)),columns=list('bcd'),
             index=['Ohio','Texas','colorado'])
df2=DataFrame(np.arange(12.).reshape((4,3)),columns=list('bde'),
            index=['Utah','Ohio','Texas','Oregon'])
print(df1)
print(df2)

            b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
colorado  6.0  7.0  8.0
          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0


In [108]:
df1+df2

b   c     d   e
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN
colorado  NaN NaN   NaN NaN

In [109]:
df1=DataFrame(np.arange(12.).reshape((3,4)),columns=list('abcd'))
df2=DataFrame(np.arange(20.).reshape((4,5)),columns=list('abcde'))
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [110]:
df1.add(df2,fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [111]:
df1.reindex(columns=df2.columns,fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [112]:
arr=np.arange(12.).reshape((3,4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [113]:
arr[0]

array([0., 1., 2., 3.])

In [114]:
arr-arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [115]:
frame=DataFrame(np.arange(12.).reshape((4,3)),columns=list('bde'),
               index=['Utah','Ohio','Texas','Oregon'])

In [117]:
series2=Series(range(3),index=['b','e','f'])
frame+series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [118]:
series3=frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [119]:
frame.sub(series3,axis=0)

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [120]:
frame=DataFrame(np.random.randn(4,3),columns=list('bde'),
               index=['Utah','Ohio','Texas','Oregon'])
frame

b         d         e
Utah   -1.298125  0.016175 -2.414864
Ohio    1.331172  0.463647 -0.994157
Texas   0.563827 -1.783903 -0.128420
Oregon -2.141159  1.419793  1.430396

In [121]:
np.abs(frame)

b         d         e
Utah    1.298125  0.016175  2.414864
Ohio    1.331172  0.463647  0.994157
Texas   0.563827  1.783903  0.128420
Oregon  2.141159  1.419793  1.430396

In [122]:
f=lambda x:x.max()-x.min()
frame.apply(f)

b    3.472331
d    3.203697
e    3.845260
dtype: float64

In [123]:
frame.apply(f, axis=1)

Utah      2.431039
Ohio      2.325328
Texas     2.347730
Oregon    3.571555
dtype: float64

In [124]:
def f(x):
    return Series([x.min(),x.max()],index=['min','max'])
frame.apply(f)

b         d         e
min -2.141159 -1.783903 -2.414864
max  1.331172  1.419793  1.430396

In [125]:
format=lambda x: '%.2f' % x
frame.applymap(format)

b      d      e
Utah    -1.30   0.02  -2.41
Ohio     1.33   0.46  -0.99
Texas    0.56  -1.78  -0.13
Oregon  -2.14   1.42   1.43

In [126]:
frame['e'].map(format)

Utah      -2.41
Ohio      -0.99
Texas     -0.13
Oregon     1.43
Name: e, dtype: object

In [127]:
obj=Series(range(4),index=['d','a','b','c'])
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [128]:
frame=DataFrame(np.arange(8).reshape((2,4)),
               index=['three','one'],columns=['d','a','b','c'])
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [129]:
frame.sort_index(axis=1,ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [130]:
obj=Series([4,7,-3,2])

In [131]:
frame=DataFrame({'b':[4,7,-3,2],'a':[0,1,0,1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [132]:
frame.sort_index

<bound method DataFrame.sort_index of    b  a
0  4  0
1  7  1
2 -3  0
3  2  1>

In [133]:
obj=Series([7,-5,7,4,2,0,4])
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [134]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [135]:
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [136]:
frame=DataFrame({'b':[4.3,7,-3,2],'a':[0,1,0,1],
                'c':[-2,5,8,-2.5]})
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [137]:
frame.rank(axis=1)

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [138]:
obj=Series(range(5),index=['a','a','b','b','c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [139]:
obj.index.is_unique

False

In [140]:
print(obj['b'])
print(obj['c'])

b    2
b    3
dtype: int64
4


In [141]:
df=DataFrame([[1.4,np.nan],[7.1,-4.5],[np.nan,np.nan],[0.75,-1.3]],
            index=['a','b','c','d'],
            columns=['one','two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [142]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [143]:
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [144]:
df.mean(axis=1, skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [146]:
df.idxmax()

one    b
two    d
dtype: object

In [147]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [148]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [149]:
obj=Series(['a','a','b','c']*4)
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [152]:
obj=Series(['c','a','d','a','a','b','b','c','c'])
uniques=obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [153]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [154]:
pd.value_counts(obj.values,sort=False)

a    3
d    1
b    2
c    3
dtype: int64

In [156]:
mask=obj.isin(['b','c'])
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [157]:
data=DataFrame({'Qu1':[1,3,4,3,4],
               'Qu2':[2,3,1,2,3],
               'Qu3':[1,5,2,4,4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [159]:
result=data.apply(pd.value_counts).fillna(0)
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

In [160]:
string_data=Series(['aardvark','artichock',np.nan,'avocado'])
string_data

0     aardvark
1    artichock
2          NaN
3      avocado
dtype: object

In [161]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [162]:
from numpy import nan as NA
data=Series([1,NA,3.5,NA,7])
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [163]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [164]:
data=DataFrame([[1.,6.5,3.],[1.,NA,NA],
               [NA,NA,NA],[NA,6.5,3.]])
cleaned=data.dropna()
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [165]:
cleaned

0    1    2
0  1.0  6.5  3.0

In [167]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [168]:
data.dropna(axis=1,how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [176]:
df=DataFrame(np.random.randn(7,3))
df

0         1         2
0  1.353352  0.686076 -0.949490
1 -0.875820  0.632107 -0.595383
2 -0.926071 -2.317606  1.525707
3 -0.601943 -0.344584 -0.994562
4  0.669396  0.303399  1.715948
5 -0.242537  0.362270 -0.960452
6 -1.652758 -0.896531 -0.640327

In [177]:
df.loc[:4,1]=NA
df.loc[:2,2]=NA
df

0         1         2
0  1.353352       NaN       NaN
1 -0.875820       NaN       NaN
2 -0.926071       NaN       NaN
3 -0.601943       NaN -0.994562
4  0.669396       NaN  1.715948
5 -0.242537  0.362270 -0.960452
6 -1.652758 -0.896531 -0.640327

In [178]:
df.dropna(thresh=3)

0         1         2
5 -0.242537  0.362270 -0.960452
6 -1.652758 -0.896531 -0.640327

In [179]:
df.fillna(0)

0         1         2
0  1.353352  0.000000  0.000000
1 -0.875820  0.000000  0.000000
2 -0.926071  0.000000  0.000000
3 -0.601943  0.000000 -0.994562
4  0.669396  0.000000  1.715948
5 -0.242537  0.362270 -0.960452
6 -1.652758 -0.896531 -0.640327

In [180]:
df.fillna({1:0.5,3:-1})

0         1         2
0  1.353352  0.500000       NaN
1 -0.875820  0.500000       NaN
2 -0.926071  0.500000       NaN
3 -0.601943  0.500000 -0.994562
4  0.669396  0.500000  1.715948
5 -0.242537  0.362270 -0.960452
6 -1.652758 -0.896531 -0.640327

In [181]:
df=DataFrame(np.random.randn(6,3))
df.loc[2:,1]=NA
df.loc[4:,2]=NA
df

0         1         2
0 -0.411874 -0.224286  0.876652
1  0.795773  0.089449  0.676346
2 -0.154893       NaN -0.806709
3  1.829073       NaN -0.495755
4 -0.470217       NaN       NaN
5 -1.761681       NaN       NaN

In [182]:
df.fillna(method='ffill')

0         1         2
0 -0.411874 -0.224286  0.876652
1  0.795773  0.089449  0.676346
2 -0.154893  0.089449 -0.806709
3  1.829073  0.089449 -0.495755
4 -0.470217  0.089449 -0.495755
5 -1.761681  0.089449 -0.495755

In [183]:
data=Series([1.,NA,3.5,NA,7])
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [184]:
data=Series(np.random.randn(10),
           index=[['a','a','a','b','b','b','c','c','d','d'],
                 [1,2,3,1,2,3,1,2,2,3]])
data

a  1   -1.084764
   2    1.551942
   3    1.839414
b  1    0.586876
   2   -0.209762
   3    1.152927
c  1   -0.024338
   2   -0.601266
d  2    0.676445
   3   -0.473748
dtype: float64

In [185]:
data.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 2),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )

In [186]:
data['b']

1    0.586876
2   -0.209762
3    1.152927
dtype: float64

In [187]:
data[:,2]

a    1.551942
b   -0.209762
c   -0.601266
d    0.676445
dtype: float64

In [188]:
data.unstack()

1         2         3
a -1.084764  1.551942  1.839414
b  0.586876 -0.209762  1.152927
c -0.024338 -0.601266       NaN
d       NaN  0.676445 -0.473748

In [189]:
frame=DataFrame(np.arange(12).reshape(4,3),
               index=[['a','a','b','b'],[1,2,1,2]],
               columns=[['Ohio','Ohio','Colorado'],
                       ['Green','Red','Green']])
frame

Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [190]:
frame.index.names=['key1','key2']
frame.columns.names=['state','color']
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [191]:
frame.swaplevel('key1','key2')

state      Ohio     Colorado
color     Green Red    Green
key2 key1                   
1    a        0   1        2
2    a        3   4        5
1    b        6   7        8
2    b        9  10       11

In [193]:
frame.sum(level='key2')

state  Ohio     Colorado
color Green Red    Green
key2                    
1         6   8       10
2        12  14       16

In [194]:
frame=DataFrame({'a':range(7),'b':range(7,0,-1),
                'c':['one','one','one','two','two','two','two'],
                'd':[0,1,2,0,1,2,3]})
frame

a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [196]:
frame2=frame.set_index(['c','d'])
frame2

a  b
c   d      
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [197]:
frame.set_index(['c','d'],drop=False)

a  b    c  d
c   d              
one 0  0  7  one  0
    1  1  6  one  1
    2  2  5  one  2
two 0  3  4  two  0
    1  4  3  two  1
    2  5  2  two  2
    3  6  1  two  3

In [198]:
frame2.reset_index()

c  d  a  b
0  one  0  0  7
1  one  1  1  6
2  one  2  2  5
3  two  0  3  4
4  two  1  4  3
5  two  2  5  2
6  two  3  6  1